name: file tree

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Install tree
        run: |
          brew upadte
          brew install tree
      - name: Excute tree
        run: time tree | tee filetreelist.txt
