name: Verify file

on:
  push:
  pull_request:
jobs:
  verify:
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXEC_WF == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [[ -f "${{ vars.FILE_TO_CHECK }}" ]]; then
            echo "${{ vars.FILE_TO_CHECK }} exists."
          else
            echo "${{ vars.FILE_TO_CHECK }} file needs to be added to ${{ github.repository }}!" && exit 1
          fi
