name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
jobs:
  #이 잡은 레포로부터 코드를 체크아웃한다.......!!!
  build:
    runs-on: self-hosted
    steps:
      - name: Install tree
        run: |
          brew upadte
          brew install tree
      - name: Excute tree
        run: time tree | tee filetreelist.txt
